VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "MxMHMB52_A_PhTmpn"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Text
Option Explicit
Const CMod$ = "MxMHMB52_Ph_PhTmpn."
Function L4$(Qtp$):     L4 = RplQ(Qtp, "L4"):   End Function
Function L3$(Qtp$):     L3 = RplQ(Qtp, "L3"):   End Function
Function L2$(Qtp$):     L2 = RplQ(Qtp, "L2"):   End Function
Function L1$(Qtp$):     L1 = RplQ(Qtp, "L1"):   End Function
Function LSku$(Qtp$): LSku = RplQ(Qtp, "LSku"): End Function
Function LStm$(Qtp$): LStm = RplQ(Qtp, "LStm"): End Function
Function LBus$(Qtp$): LBus = RplQ(Qtp, "LBus"): End Function
