VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "MxMHMB52_MHBtnChk"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Text
Option Explicit

Sub Rpt():           ChkAcBtn FrmnRpt:           End Sub
Sub LoadSku():       ChkAcBtn FrmnLoadSku:       End Sub
Sub LoadZHT0():      ChkAcBtn FrmnLoadZHT0:      End Sub
Sub LoadPH():        ChkAcBtn FrmnLoadPH:        End Sub
Sub LoadFc():        ChkAcBtn FrmnLoadFc:        End Sub
Sub MacauCalcRate(): ChkAcBtn FrmnMacauCalcRate: End Sub
