VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "MxMHMB52_A_TbPh"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Text
Option Explicit
Sub RfhFldSno():       Static W As New MxMHMB52_A_TbPh_RfhFldSno: W.RfhFldSno:             End Sub
Sub RfhFldSrt():       Static W As New MxMHMB52_A_TbPh_RfhFldSrt: W.RfhFldSrt:             End Sub
Sub RfhFldWithOHXxx(): Static W As New MxMHMB52_A_TbPh_RfhFldWithOHXXX: W.RfhFldWithOHXxx: End Sub
