VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "MxMHMB52_MHBtnRen"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Text
Option Explicit
Sub Rpt():           RenAcBtn FrmnRpt:           End Sub
Sub LoadSku():       RenAcBtn FrmnLoadSku:       End Sub
Sub LoadZHT0():      RenAcBtn FrmnLoadZHT0:      End Sub
Sub LoadPH():        RenAcBtn FrmnLoadPH:        End Sub
Sub LoadFc():        RenAcBtn FrmnLoadFc:        End Sub
Sub MacauCalcRate(): RenAcBtn FrmnMacauCalcRate: End Sub
