SELECT qPHL4.*, qPHL1.PHNam, qPHL2.PHBrd, qPHL3.PHQGp
FROM ((qPHL4 INNER JOIN qPHL1 ON qPHL4.PHL1 = qPHL1.PHL1) INNER JOIN qPHL2 ON qPHL4.PHL2 = qPHL2.PHL2) INNER JOIN qPHL3 ON qPHL4.PHL3 = qPHL3.PHL3;
